name: Prefect Cloud Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "workflows/create_deployments.py"
      - ".github/workflows/prefect-cloud-deploy.yaml"

jobs:
  deploy_flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install prefect dependencies
        run: |
          python -m pip install prefect prefect-github
      
      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v2
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: ${{ secrets.PREFECT_WORKSPACE }}

      - name: Run Create Deployments script
        run: |
          python workflows/create_deployments.py